//HintName: Test_TestNamespace.ITestInterface.g.cs
// <auto-generated/>
namespace TestNamespace;

public partial class Test : TestNamespace.ITestInterface
{
    public int GetInt()
        => throw new System.NotImplementedException();
}
