//HintName: AutoScopeAttribute.g.cs
// <auto-generated/>
namespace AutoScoper
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class AutoScopeAttribute : System.Attribute
    {
        public AutoScopeAttribute(params System.Type[] interfacesType)
        {
            InterfacesType = interfacesType;
        }

        public System.Type[] InterfacesType { get; }
    }
}