//HintName: Test_TestNamespace.Complex.Nested.ITestInterface.g.cs
// <auto-generated/>
namespace TestNamespace.Complex.Nested;

public partial class Test : TestNamespace.Complex.Nested.ITestInterface
{
    public int GetInt()
        => throw new System.NotImplementedException();
}
